### ISSUE TITLE
import issue

### ISSUE THREAD

**Issue by sree93** [smartstudy/media_converter#27]
Traceback (most recent call last):
  File "download.py", line 8, in <module>
    from media_converter import MediaConverter
  File "/home/srinath/.virtualenvs/youtube/local/lib/python2.7/site-packages/media_converter/__init__.py", line 1, in <module>
    from media_converter.media_converter import MediaConverter
  File "/home/srinath/.virtualenvs/youtube/local/lib/python2.7/site-packages/media_converter/media_converter.py", line 93
    self._command.extend([f'-disposition:{identifier}:{track_index}',
                                                                   ^
SyntaxError: invalid syntax

**Comment by ecleya** [comment]
currently it supports only python 3.6 or later.

it may take some time to support python2.
